# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/adrianliechti/wingman-reader

tasks:
  run:
    cmds:
      - docker run -it --rm -p 50051:50051 $(docker build . -q)
      
  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest

  generate:
    cmds:
      - curl -Lo extractor.proto https://raw.githubusercontent.com/adrianliechti/wingman/refs/heads/main/pkg/extractor/custom/extractor.proto
      - pip install grpcio-tools grpcio-reflection
      - python -m grpc_tools.protoc -I . --python_out=. --pyi_out=. --grpc_python_out=. extractor.proto
